import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/utils/context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Siscom",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AuthProvider> {/* Wrap the entire app with AuthProvider */}
          {children}
        </AuthProvider>
        </body>
    </html>
  );
}
